name: Code style check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: '**/*.py'

      - name: Setup Python env
        uses: actions/setup-python@v3

      - name: Install black and reorder-python-imports
        run: pip install isort==5.10.1 black==22.3.0

      - name: ISort and Black
        run: |
          isort --check-only --quiet --diff ${{ steps.changed-files.outputs.all_changed_files }}
          black --check -S --line-length 120 --diff ${{ steps.changed-files.outputs.all_changed_files }}
